name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # وقتی به main push شد اجرا می‌شود

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # گرفتن سورس از GitHub
      - name: Checkout repository
        uses: actions/checkout@v3

      # راه‌اندازی Buildx برای multi-platform و cache بهتر
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ورود به Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ساخت و Push کردن Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bookkhooneh:latest
